defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .


model_filepath: "/home/casey/Projects/Hip-Inserter/models/sleap_projects/models/7-points-3230831_174033.single_instance.n=300"

# camera: True
# camera: "/home/casey/Projects/Hip-Inserter/data/collection/20231231_191639"
# camera: "/home/casey/Projects/Hip-Inserter/data/collection/20231231_191742"
# camera: "/home/casey/Projects/Hip-Inserter/data/collection/20231231_191825"

# camera: "/home/casey/Projects/Hip-Inserter/data/collection/20240107_183340"
# camera: "/home/casey/Projects/Hip-Inserter/data/collection/20240107_183449"
camera: "/home/casey/Projects/Hip-Inserter/data/collection/20240107_183609"
# camera: "/home/casey/Projects/Hip-Inserter/data/collection/20240107_183743"
# camera: "/home/casey/Projects/Hip-Inserter/data/collection/20240107_183830"
# camera: "/home/casey/Projects/Hip-Inserter/data/collection/20240107_183916"
# camera: "/home/casey/Projects/Hip-Inserter/data/collection/20240107_183955"

buffers:
  time_delta_max: 0.2
  pixel_delta_max: 2
  num_buffers: 5

horozontal_check:
  pixel_delta_max: 2

principle_axis_var_check:
  var_max: 0.0003
  points_min: 3

distance_check:
  distance_min: 0.1

geometry_check:
  distance_delta_max: 0.02
  points_min: 3

moving_average:
  roll: 0.2
  pitch: 0.5
  depth: 0.5

depth_estimate:
  points_idx: 2

draw_vector:
  n_points: 500

show_output: True
# record_output: "/home/casey/Videos/output_test.mp4"
record:
  # output: "/home/casey/Projects/Hip-Inserter/analysis/outputs/20231231_191639/output_final.mp4"
  # output: "/home/casey/Projects/Hip-Inserter/analysis/outputs/20231231_191742/output_final.mp4"
  # output: "/home/casey/Projects/Hip-Inserter/analysis/outputs/20231231_191825/output_final.mp4"
  
  # output: "/home/casey/Projects/Hip-Inserter/analysis/outputs/20240107_183340/output_final.mp4"
  # output: "/home/casey/Projects/Hip-Inserter/analysis/outputs/20240107_183449/output_final.mp4"
  output: "/home/casey/Projects/Hip-Inserter/analysis/outputs/20240107_183609/output_final.mp4"
  # output: "/home/casey/Projects/Hip-Inserter/analysis/outputs/20240107_183743/output_final.mp4"
  # output: "/home/casey/Projects/Hip-Inserter/analysis/outputs/20240107_183830/output_final.mp4"
  # output: "/home/casey/Projects/Hip-Inserter/analysis/outputs/20240107_183916/output_final.mp4"
  # output: "/home/casey/Projects/Hip-Inserter/analysis/outputs/20240107_183955/output_final.mp4"
  fps: 10